let rock=document.getElementById("r");         /*input get vaiable declare */
let paper=document.getElementById("p");
let sisor=document.getElementById("s");
let userscore=0;
let computerscore=0;

                                        // random computer choice generated by pre-defined function
function compchoice(){
        let choice=['r','p','s'];
        let ch=Math.floor(Math.random()*3);
        return choice[ch]
}

                                        // when user win call win function
                                        //this function increse user score
function win(){
        userscore++;
        document.getElementById("user-score").innerHTML=userscore;
        document.getElementById("comp-score").innerHTML=computerscore;
        document.getElementById("result").innerHTML='you are win and computer is lost';
console.log("you are win");
}
                                        /* when user call lost function
                                        this function increse computer score   */
function lost(){
        computerscore++;
        document.getElementById("user-score").innerHTML=userscore;
        document.getElementById("comp-score").innerHTML=computerscore;
        document.getElementById("result").innerHTML='you are lost and computer is win';
console.log("you are lost");
}
                                                /* when user choice and computer choice is same
                                        the draw function is call and this function not increse any values  */
function draw(){
        document.getElementById("user-score").innerHTML=userscore;
        document.getElementById("comp-score").innerHTML=computerscore;
        document.getElementById("result").innerHTML='this match is draw';
console.log("this match is draw");
}






function cho(userchoice){             //default choice is defined
        let comp=compchoice();
        console.log(userchoice+comp);
        switch(userchoice+comp){
                case"rs":
                case"pr":
                case"sp":
                win()
                break;
                case"sr":
                case"rp":
                case"ps":
                lost()
                break;
                case"rr":
                case"ss":
                case"pp":
                draw()
                break;
        }
}



                                                // html input variable assigned by click event

function main(){
rock.addEventListener('click',()=>{cho('r')})
paper.addEventListener('click',()=>{cho("p")})
sisor.addEventListener('click',()=>{cho("s")})
}



main();


/*                                   this program created by madhanraj-official                                                              */
                